name: CI workflow
on: workflow_dispatch

jobs:
  workdir:
    runs-on: ubuntu-latest
    steps:
      - name: show working dir
        run: |
          pwd
          cd ..
          ls -ll
          df -h
          echo " my message"
      - name: upload files
        run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            path/to/artifact/world.txt
            demo.yml



# jobs:
#   build-job:
#   runs-on: ubuntu-latest
#   steps:
#     - name: get code
#       uses: actions/checkout@v5