name: CI workflow
on: workflow_dispatch

jobs:
  workdir:
    runs-on: ubuntu-latest
    steps:
      - name: show working dir
        run: |
          pwd
          cd ..
          ls -ll
          df -h
          echo " my message"
      - name: upload files
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
              /home/runner/work
      - name: download files
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: output the content
        run: ls          



# jobs:
#   build-job:
#   runs-on: ubuntu-latest
#   steps:
#     - name: get code
#       uses: actions/checkout@v5