name: CI workflow
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.output.test }}
    steps:
      - name: show working dir
        run: |
          pwd
          cd ..
          ls -ll
          df -h
          echo " my message"
      - name: upload files
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
              /home/runner/work
      - name: publish output
        id: step1
        run: |
          echo "test=abcdef" >> $GITHUB_OUTPUT
          echo "${{ toJSON.GITHUB_OUTPUT }}"

      - name: download files
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: output the content
        run: ls 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: print output from previous job
        run: | 
          echo "${{ needs.job1.outputs.output1 }}"
          echo "output contect object"




# jobs:
#   build-job:
#   runs-on: ubuntu-latest
#   steps:
#     - name: get code
#       uses: actions/checkout@v5